name: Push branch workflow ghcr develop

on:
  push:
    branches:
      - develop

jobs:
  build-branch:
    name: Build branch and run unit tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Java
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Maven for GitHub Packages
        uses: ./.github/actions/setup-maven
        with:
          username: ${{ secrets.USERNAME_GITHUB }}
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Build and Test
        working-directory: .
        run: mvn clean install -Dspring.profiles.active=test

  push-ghcr:
    name: Build branch and push ghcr.io
    runs-on: ubuntu-22.04
    needs: build-branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup Maven for GitHub Packages
        uses: ./.github/actions/setup-maven
        with:
          username: ${{ secrets.USERNAME_GITHUB }}
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Copy settings.xml for Docker Build
        run: cp ~/.m2/settings.xml ./

      - name: Build Docker Image
        run: docker build -t ghcr.io/sursindmitry/berkut-service:develop-${{ github.sha }} .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u ${{ secrets.USERNAME_GITHUB }} --password-stdin

      - name: Push Docker Image
        run: docker push ghcr.io/sursindmitry/berkut-service:develop-${{ github.sha }}